-- ZD-181b: Add RAG document storage schema (documents + chunks + embeddings).

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
	proposal_id BIGINT NOT NULL REFERENCES public.proposals(id) ON DELETE CASCADE,
	round INT NOT NULL CHECK (round >= 0 AND round <= 7),
	user_id UUID REFERENCES auth.users(id),
	filename TEXT NOT NULL CHECK (char_length(filename) > 0),
	storage_path TEXT NOT NULL CHECK (char_length(storage_path) > 0),
	mime_type TEXT,
	size_bytes BIGINT,
	metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_documents_proposal_round
	ON public.documents (proposal_id, round);
CREATE INDEX IF NOT EXISTS idx_documents_created_at
	ON public.documents (created_at DESC);

CREATE TABLE IF NOT EXISTS public.document_chunks (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
	document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
	proposal_id BIGINT NOT NULL REFERENCES public.proposals(id) ON DELETE CASCADE,
	round INT NOT NULL CHECK (round >= 0 AND round <= 7),
	chunk_index INT NOT NULL,
	content TEXT NOT NULL CHECK (char_length(content) > 0),
	embedding extensions.vector(1536),
	metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
	CONSTRAINT document_chunks_unique_idx UNIQUE (document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_document_chunks_document
	ON public.document_chunks (document_id);
CREATE INDEX IF NOT EXISTS idx_document_chunks_proposal_round
	ON public.document_chunks (proposal_id, round);

-- Vector index for similarity search (cosine distance).
CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding
	ON public.document_chunks
	USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- LangChain-compatible similarity search function.
CREATE OR REPLACE FUNCTION public.match_documents(
	query_embedding extensions.vector(1536),
	match_count INT DEFAULT NULL,
	filter JSONB DEFAULT '{}'::jsonb
) RETURNS TABLE (
	id BIGINT,
	content TEXT,
	metadata JSONB,
	similarity FLOAT
)
LANGUAGE plpgsql STABLE
AS $$
BEGIN
	RETURN QUERY
	SELECT
		document_chunks.id,
		document_chunks.content,
		document_chunks.metadata,
		1 - (document_chunks.embedding <=> query_embedding) AS similarity
	FROM public.document_chunks
	WHERE document_chunks.metadata @> filter
	ORDER BY document_chunks.embedding <=> query_embedding
	LIMIT match_count;
END;
$$;

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_chunks ENABLE ROW LEVEL SECURITY;

-- Documents RLS
CREATE POLICY "Anyone can read documents"
	ON public.documents
	FOR SELECT
	USING (true);

CREATE POLICY "Anyone can insert documents"
	ON public.documents
	FOR INSERT
	TO anon, authenticated
	WITH CHECK (true);

CREATE POLICY "Users can update their own documents"
	ON public.documents
	FOR UPDATE
	TO authenticated
	USING (auth.uid() = user_id)
	WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own documents"
	ON public.documents
	FOR DELETE
	TO authenticated
	USING (auth.uid() = user_id);

-- Document chunks RLS
CREATE POLICY "Anyone can read document chunks"
	ON public.document_chunks
	FOR SELECT
	USING (true);

CREATE POLICY "Anyone can insert document chunks"
	ON public.document_chunks
	FOR INSERT
	TO anon, authenticated
	WITH CHECK (true);
