export const ORGANIZATION_SHORT = 'AVG';
export const ORGANIZATION_FULL = 'Aquário Vasco da Gama';
export const ORGANIZATION_NAME = ORGANIZATION_FULL;
export const PEDAGOGIC_ROUNDS_TIMER_MINUTES = 1;
export const PEDAGOGIC_ROUND7_USER_PROMPTS_DEFAULT = 5;
export const PEDAGOGIC_ROUND7_USER_PROMPTS_MAX = 10;
